name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependências
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typechecking
        run: npm run test:ts

      - name: Testes
        run: exit 0

      - name: Build
        env:
          NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
        run: npm run build
